### PR TITLE
Fixed some compiler warnings, like int compared with uint,   uninitia…

### PR DESCRIPTION
**Pull request by iceman1001**
…lized vars.

### CODE REVIEW

**Comment by msoos** [comment]
Thanks! :)

**Comment by iceman1001** [comment]
Fast question,  can I modell a block crypto like TEA with grainofsalt or it this only for stream ciphers?

**Comment by msoos** [comment]
Not as far as I know. I suggest you try modelling in SMT first, though. Take a look at SMTLib and STP -- I also help maintain that project, it's on GitHub: github.com/stp/stp

**Comment by hadipourh** [comment]
Hello there
Fast question, can I model a **_word based_** stream cipher such as Snow with grainofsalt or it is only for **_bitwise_** stream ciphers?

**Comment by msoos** [comment]
It's for bitwise only :( But you can *definitely* model it in STP, which is great. Use SMT-LIB standard input and then you can even run it on many different systems like boolector and Z3. STP is pretty fast, boolector is faster but maybe not as free to use. Z3 is a lot slower. There are other options, too, just check out the bitvector arithmetic SMT competitions! Good luck!

PS: There are many different ciphers out there modelled in SMT-Lib, check them out, search on Google :)

**Pull request merged**
